name: TownyBlueprints
version: '${0.1.0.1}'
main: com.townyblueprints.TownyBlueprints
api-version: '1.21'
depend: [Towny]
softdepend: [dynmap-towny, WorldEdit]
authors: [ParvatiMountains]
description: A Towny addon that adds blueprint-based town features

permissions:
  townyblueprints.use:
    description: Allows basic plugin usage
    default: true
  townyblueprints.admin:
    description: Allows administrative control
    default: op
  townyblueprints.collect:
    description: Allows collecting resources from blueprints
    default: op
  townyblueprints.visualize:
    description: Allows town mayors to use blueprint visualization
    default: true
  townyblueprints.remove:
    description: Allows removing blueprints
    default: op
  townyblueprints.assistant:
    description: Grants town assistant privileges
    default: false
  townyblueprints.upgrade:
    description: Allows upgrading blueprints
    default: true
  townyblueprints.nation.tax:
    description: Allows setting nation tax rates
    default: op
  townyblueprints.blueprint.*:
    description: Allows usage of all blueprints
    default: op
  townyblueprints.blueprint.farm:
    description: Allows usage of the farm blueprint
    default: true
  townyblueprints.blueprint.mine:
    description: Allows usage of the mine blueprint
    default: true
  townyblueprints.blueprint.warehouse:
    description: Allows usage of the warehouse blueprint
    default: true
  townyblueprints.blueprint.quarry.*:
    description: Allows usage of all quarry blueprints
    default: op
    children:
      townyblueprints.blueprint.quarry.1: true
      townyblueprints.blueprint.quarry.2: true
      townyblueprints.blueprint.quarry.3: true
  townyblueprints.blueprint.quarry.1:
    description: Allows usage of tier 1 quarry blueprint
    default: true
  townyblueprints.blueprint.quarry.2:
    description: Allows usage of tier 2 quarry blueprint
    default: true
  townyblueprints.blueprint.quarry.3:
    description: Allows usage of tier 3 quarry blueprint
    default: true